### ISSUE TITLE
please have debian package versioning follow the ami version

### ISSUE THREAD

**Issue by egonw** [ContentMine/ami#53]
Instead of 0.1-SNAPSHOT, please consider using the versions used for AMI releases, which is 0.2.24 now.

**Comment by petermr** [comment]
Exactly what we will be doing in the next few days

On Wed, Apr 27, 2016 at 11:53 PM, Egon Willighⓐgen 0000-0001-7542-0286 <
notifications@github.com> wrote:

> Instead of 0.1-SNAPSHOT, please consider using the versions used for AMI
> releases, which is 0.2.24 now.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/ContentMine/ami/issues/53

## 

Peter Murray-Rust
Reader in Molecular Informatics
Unilever Centre, Dep. Of Chemistry
University of Cambridge
CB2 1EW, UK
+44-1223-763069

**Comment by egonw** [comment]
I believe this is fixed now.
